### ISSUE TITLE
Awesome! Update for last season?

### ISSUE THREAD

**Issue by busterroni** [devstopfix/nfl_results#2]
Thanks for this! Is there any chance you could update it through 2015?

Also, any update on obtaining data pre-1976? If you could get data for that, that would be fantastic. Let me know if you need any help.

**Comment by devstopfix** [comment]
@busterroni  Just noticed your comment - none of the forks seem to be ahead of me unfortunately. I don't plan to update this dataset anytime soon as there are online databases that provide scores
